const cat = {
  WheyProtein: "Whey Protein",
  ProteinShake: "Protein Shake",
  ProteinBar: "Protein Bar",
  CordycepsShilajit: "Cordyceps ShilaJit",
  CordySterone: "CordySterone",
  CordyTesto: "CordyTesto",
  CordyShila: "CordyShila",
  tvAndAudio: "tvAndAudio",
  tvBox: "tvBox",
  powerTools: "powerTools",
  headphones: "headphones",
  cellPhones: "cellPhones",
  smartWatches: "smartWatches",
  gameAndVideo: "gameAndVideo",
  robotClean: "robotClean",
  sportWatches: "sportWatches",
  tablets: "tablets",
  computersAndLaptop: "computersAndLaptop",
  camerasAndPhotos: "camerasAndPhotos",
};
export const categories = [
  {
    _id: 1001,
    name: "ProteinWhey",
    image: "https://i.ibb.co/kM0FR2h/cat-Tv-Audio.webp",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "WheyProtein",
  },
  {
    _id: 1002,
    name: "Protein",
    image: "https://i.ibb.co/X2vFZWg/cordytesto-shilajit-testorone.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "WheyProtein",
  },
  {
    _id: 1003,
    name: "CordyTesto",
    image: "https://i.ibb.co/RSJbNwL/cordyshala-60ml.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "CordyTesto",
  },
  {
    _id: 1004,
    name: "CordySterone",
    image: "https://i.ibb.co/99cXbCT/cordy-testorone-legend.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "CordySterone",
  },
  {
    _id: 1005,
    name: "CordyShila",
    image: "https://i.ibb.co/KxdL6By/cordytesto.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "CordyShila",
  },
  {
    _id: 1006,
    name: "CordycepsShilajit",
    image: "https://i.ibb.co/Tk2Vcb1/cordyshila-II.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "CordycepsShilajit",
  },
];

export const highlightsProducts = [
  {
    _id: 3001,
    name: "New Deals at Best Prices",
    title: "From $40.00",
    buttonTitle: "Browse Deals",
    image: "https://i.ibb.co/G951N5B/highlights-One.webp",
    _base: "/product",
    color: "#000000",
  },
  {
    _id: 3002,
    name: "Colorful Redmi  Note 6 Pro",
    title: "From $40.00",
    buttonTitle: "Shop Cellphone",
    image: "https://i.ibb.co/bLRNKGq/highlights-Two.webp",
    _base: "/category/cellPhones",
    color: "#ffffff",
  },
  {
    _id: 3003,
    name: "1000 mAh Power Bank",
    title: "From $40.00",
    buttonTitle: "Shop Now",
    image: "https://i.ibb.co/svWYstT/highlights-Three.webp",
    _base: "/product",
    color: "#ffffff",
  },
];

export const blogsData = [
  {
    _id: 4001,
    image: "https://i.ibb.co/XbQf5HS/blogOne.webp",
    title: "iPhone 15 rear camera design will be available",
    _base: "Technology",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
  },
  {
    _id: 4002,
    image: "https://i.ibb.co/wzNpcwp/blogTwo.webp",
    title: "Setup your surround sound speaker",
    _base: "Samrt thing",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
  },
  {
    _id: 4003,
    image: "https://i.ibb.co/prdZ3s8/blog-Three.webp",
    title: "Hook up a receiver for your home theater",
    _base: "Life style",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
  },
];

export const products = [
  {
    _id: 2001,
    name: "Divoom Tivoo Portable Bluetooth Speaker Smart Clock Alarm Pixel Art DIY By App LED Light Sign In Decoration Unique Gift",
    images: [
      "https://i.ibb.co/m6ZN7LX/soundBox.webp",
      "https://i.ibb.co/m6ZN7LX/soundBox.webp",
      "https://i.ibb.co/wdV3b9q/vaccum.webp",
      "https://i.ibb.co/tcdSfrr/blueGun.jpg",
      "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 600,
    discountedPrice: 580,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "TV & Audio",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Samsung",
    isStock: true,
    overView: "Blutooth Speaker",
    isNew: true,
    _base: cat?.WheyProtein,
  },
  {
    _id: 2002,
    name: "Codyceps Shilajit and cordysterone and cordytesto all in one ",
    images: [
      "https://i.ibb.co/X2vFZWg/cordytesto-shilajit-testorone.jpg",
      "https://i.ibb.co/RSJbNwL/cordyshala-60ml.jpg",
      "https://i.ibb.co/99cXbCT/cordy-testorone-legend.jpg",
      "https://i.ibb.co/KxdL6By/cordytesto.jpg",
      "https://i.ibb.co/dP5g4zY/cordy-sterone-main-II.jpg",
      "https://i.ibb.co/Tk2Vcb1/cordyshila-II.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1000,
    discountedPrice: 900,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "CordyTesto",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "CordyCeps",
    isStock: true,
    overView: "WheyProtein",
    isNew: true,
    _base: cat?.CordyShila,
  },
  {
    _id: 2003,
    name: "Codyceps Shilajit and cordysterone and cordytesto all in one ",
    images: [
      "https://i.ibb.co/X2vFZWg/cordytesto-shilajit-testorone.jpg",
      "https://i.ibb.co/RSJbNwL/cordyshala-60ml.jpg",
      "https://i.ibb.co/99cXbCT/cordy-testorone-legend.jpg",
      "https://i.ibb.co/KxdL6By/cordytesto.jpg",
      "https://i.ibb.co/dP5g4zY/cordy-sterone-main-II.jpg",
      "https://i.ibb.co/Tk2Vcb1/cordyshila-II.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1000,
    discountedPrice: 900,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "CordyTesto",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "CordyCeps",
    isStock: true,
    overView: "WheyProtein",
    isNew: true,
    _base: cat?.CordyShila,
  },
  {
    _id: 2004,
    name: "Codyceps Shilajit and cordysterone and cordytesto all in one ",
    images: [
      "https://i.ibb.co/X2vFZWg/cordytesto-shilajit-testorone.jpg",
      "https://i.ibb.co/RSJbNwL/cordyshala-60ml.jpg",
      "https://i.ibb.co/99cXbCT/cordy-testorone-legend.jpg",
      "https://i.ibb.co/KxdL6By/cordytesto.jpg",
      "https://i.ibb.co/dP5g4zY/cordy-sterone-main-II.jpg",
      "https://i.ibb.co/Tk2Vcb1/cordyshila-II.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1000,
    discountedPrice: 900,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "CordyTesto",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "CordyCeps",
    isStock: true,
    overView: "WheyProtein",
    isNew: true,
    _base: cat?.CordyShila,
  },
  {
    _id: 2005,
    name: "Codyceps Shilajit and cordysterone and cordytesto all in one ",
    images: [
      "https://i.ibb.co/X2vFZWg/cordytesto-shilajit-testorone.jpg",
      "https://i.ibb.co/RSJbNwL/cordyshala-60ml.jpg",
      "https://i.ibb.co/99cXbCT/cordy-testorone-legend.jpg",
      "https://i.ibb.co/KxdL6By/cordytesto.jpg",
      "https://i.ibb.co/dP5g4zY/cordy-sterone-main-II.jpg",
      "https://i.ibb.co/Tk2Vcb1/cordyshila-II.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1000,
    discountedPrice: 900,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "CordyTesto",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "CordyCeps",
    isStock: true,
    overView: "WheyProtein",
    isNew: true,
    _base: cat?.CordyShila,
  },
  {
    _id: 2006,
    name: "Codyceps Shilajit and cordysterone and cordytesto all in one ",
    images: [
      "https://i.ibb.co/X2vFZWg/cordytesto-shilajit-testorone.jpg",
      "https://i.ibb.co/RSJbNwL/cordyshala-60ml.jpg",
      "https://i.ibb.co/99cXbCT/cordy-testorone-legend.jpg",
      "https://i.ibb.co/KxdL6By/cordytesto.jpg",
      "https://i.ibb.co/dP5g4zY/cordy-sterone-main-II.jpg",
      "https://i.ibb.co/Tk2Vcb1/cordyshila-II.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1000,
    discountedPrice: 900,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "CordyTesto",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "CordyCeps",
    isStock: true,
    overView: "WheyProtein",
    isNew: true,
    _base: cat?.CordyShila,
  },
  {
    _id: 2007,
    name: "Codyceps Shilajit and cordysterone and cordytesto all in one ",
    images: [
      "https://i.ibb.co/X2vFZWg/cordytesto-shilajit-testorone.jpg",
      "https://i.ibb.co/RSJbNwL/cordyshala-60ml.jpg",
      "https://i.ibb.co/99cXbCT/cordy-testorone-legend.jpg",
      "https://i.ibb.co/KxdL6By/cordytesto.jpg",
      "https://i.ibb.co/dP5g4zY/cordy-sterone-main-II.jpg",
      "https://i.ibb.co/Tk2Vcb1/cordyshila-II.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1000,
    discountedPrice: 900,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "CordyTesto",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "CordyCeps",
    isStock: true,
    overView: "WheyProtein",
    isNew: true,
    _base: cat?.CordyShila,
  },
  {
    _id: 2008,
    name: "Codyceps Shilajit and cordysterone and cordytesto all in one ",
    images: [
      "https://i.ibb.co/X2vFZWg/cordytesto-shilajit-testorone.jpg",
      "https://i.ibb.co/RSJbNwL/cordyshala-60ml.jpg",
      "https://i.ibb.co/99cXbCT/cordy-testorone-legend.jpg",
      "https://i.ibb.co/KxdL6By/cordytesto.jpg",
      "https://i.ibb.co/dP5g4zY/cordy-sterone-main-II.jpg",
      "https://i.ibb.co/Tk2Vcb1/cordyshila-II.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1000,
    discountedPrice: 900,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "CordyTesto",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "CordyCeps",
    isStock: true,
    overView: "WheyProtein",
    isNew: true,
    _base: cat?.CordyShila,
  },
  {
    _id: 2009,
    name: "Codyceps Shilajit and cordysterone and cordytesto all in one ",
    images: [
      "https://i.ibb.co/X2vFZWg/cordytesto-shilajit-testorone.jpg",
      "https://i.ibb.co/RSJbNwL/cordyshala-60ml.jpg",
      "https://i.ibb.co/99cXbCT/cordy-testorone-legend.jpg",
      "https://i.ibb.co/KxdL6By/cordytesto.jpg",
      "https://i.ibb.co/dP5g4zY/cordy-sterone-main-II.jpg",
      "https://i.ibb.co/Tk2Vcb1/cordyshila-II.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1000,
    discountedPrice: 900,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "CordyTesto",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "CordyCeps",
    isStock: true,
    overView: "WheyProtein",
    isNew: true,
    _base: cat?.CordyShila,
  },
  {
    _id: 2010,
    name: "Codyceps Shilajit and cordysterone and cordytesto all in one ",
    images: [
      "https://i.ibb.co/X2vFZWg/cordytesto-shilajit-testorone.jpg",
      "https://i.ibb.co/RSJbNwL/cordyshala-60ml.jpg",
      "https://i.ibb.co/99cXbCT/cordy-testorone-legend.jpg",
      "https://i.ibb.co/KxdL6By/cordytesto.jpg",
      "https://i.ibb.co/dP5g4zY/cordy-sterone-main-II.jpg",
      "https://i.ibb.co/Tk2Vcb1/cordyshila-II.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1000,
    discountedPrice: 900,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "CordyTesto",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "CordyCeps",
    isStock: true,
    overView: "WheyProtein",
    isNew: true,
    _base: cat?.CordyShila,
  },
  {
    _id: 2011,
    name: "Codyceps Shilajit and cordysterone and cordytesto all in one ",
    images: [
      "https://i.ibb.co/X2vFZWg/cordytesto-shilajit-testorone.jpg",
      "https://i.ibb.co/RSJbNwL/cordyshala-60ml.jpg",
      "https://i.ibb.co/99cXbCT/cordy-testorone-legend.jpg",
      "https://i.ibb.co/KxdL6By/cordytesto.jpg",
      "https://i.ibb.co/dP5g4zY/cordy-sterone-main-II.jpg",
      "https://i.ibb.co/Tk2Vcb1/cordyshila-II.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1000,
    discountedPrice: 900,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "CordyTesto",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "CordyCeps",
    isStock: true,
    overView: "WheyProtein",
    isNew: true,
    _base: cat?.CordyShila,
  },
  {
    _id: 2012,
    name: "Codyceps Shilajit and cordysterone and cordytesto all in one ",
    images: [
      "https://i.ibb.co/X2vFZWg/cordytesto-shilajit-testorone.jpg",
      "https://i.ibb.co/RSJbNwL/cordyshala-60ml.jpg",
      "https://i.ibb.co/99cXbCT/cordy-testorone-legend.jpg",
      "https://i.ibb.co/KxdL6By/cordytesto.jpg",
      "https://i.ibb.co/dP5g4zY/cordy-sterone-main-II.jpg",
      "https://i.ibb.co/Tk2Vcb1/cordyshila-II.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1000,
    discountedPrice: 900,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "CordyTesto",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "CordyCeps",
    isStock: true,
    overView: "WheyProtein",
    isNew: true,
    _base: cat?.CordyShila,
  },
];
